


<?php

    $servername = "localhost:3306";
    $username = "root";
    $password = "";
    $dbname = "project";

    // Create connection
    $conn = mysqli_connect($servername, $username, $password, $dbname);

    // Check connection
    if (!$conn) {
        die("Connection failed: " . mysqli_connect_error());
    }else{
        echo "done";
    }

?>

<?php

    session_start();

    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\SMTP;
    use PHPMailer\PHPMailer\Exception;
    require_once ("./include/PHPMailer.php");
    require_once ("./include/SMTP.php");
        
    $mail = new PHPMailer(true);

    try {
        //Enable SMTP debugging.
        $mail->SMTPDebug = 3;                               
        //Set PHPMailer to use SMTP.
        $mail->isSMTP();            
        //Set SMTP host name                          
        $mail->Host = "smtp.gmail.com";
        //Set this to true if SMTP host requires authentication to send email
        $mail->SMTPAuth = true;                          
        //Provide username and password     
        $mail->Username = "contact.ecera@gmail.com";                 
        $mail->Password = "bxvkfejugkniikiv";                           
        //If SMTP requires TLS encryption then set it
        $mail->SMTPSecure = "tls";                           
        //Set TCP port to connect to
        $mail->Port = 587;                                   
        
        $mail->From = "coontact.ecera@gmail.com";
        $mail->FromName = "e-Cera | Maintanance team";
        
        $mail->addAddress($_SESSION['email'] , "Dear User");
        
        $mail->isHTML(true);
        
        $bytes = openssl_random_pseudo_bytes(4);
        $pass = bin2hex($bytes);
        
        //$mail->Subject = "Devang";
        //$mail->Body = "<b>Your New Password is 👇</b><br>" . $pass;//rand(111111, 999999);
        $mail->Subject = "Reset Password";
        $mail->Body = "<p>Dear User,<br> Your new password has been <b>Resetted Successfully ✔</b><br>Now You can Login.<br><b>🔑 Your New Password =  " . $pass."</b><br><br><form action='http://localhost/HCD/project/login_page.php'><button class=btn btn-success type=submit>Click here to login</button></form>
            <br><br><br><i>This email is auto generated by e-Cera | Maintannace team no need to reply back*</i>";
        $mail->AltBody = "";
                
        $mail->send();
        //echo "Message has been sent successfully";
        //echo "<p style='color:green; font-family:verdana; font-size:20pt; background-color: lightgrey'>" . "<br><br><br>✔ Email has successfully sent check your mail-id" . "</p>";
        echo '<script>alert("✔ Email has successfully sent check your mail-id")</script>';
        header('./login_page.php');
        } catch (Exception $e) {
            echo "Mailer Error: " . $mail->ErrorInfo;
        }
        $e_mail = $_SESSION['email'];
        $sql1 = "UPDATE register_page SET password = '$pass' WHERE email = '$e_mail'";
        $exe = $conn->query($sql1);
?>